# app/words.py
# A curated list of English words that have no direct Spanish equivalent.
# Used by the Word of the Day feature on the home page.
# The daily word is selected in routes.py using the date as an index.

WORDS = [
    {
        "word": "Serendipity",
        "phonetic": "/ˌserənˈdɪpɪti/",
        "part_of_speech": "noun",
        "definition": "The occurrence of happy or lucky events by chance rather than by design.",
        "example": "Finding this school was pure serendipity.",
    },
    {
        "word": "Petrichor",
        "phonetic": "/ˈpetrɪkɔːr/",
        "part_of_speech": "noun",
        "definition": "The pleasant, earthy smell produced when rain falls on dry ground.",
        "example": "She stepped outside and breathed in the petrichor after the storm.",
    },
    {
        "word": "Wanderlust",
        "phonetic": "/ˈwɒndəlʌst/",
        "part_of_speech": "noun",
        "definition": "A strong desire to travel and explore the world.",
        "example": "Her wanderlust led her from Buenos Aires to Edinburgh.",
    },
    {
        "word": "Epiphany",
        "phonetic": "/ɪˈpɪfəni/",
        "part_of_speech": "noun",
        "definition": "A sudden, striking moment of deep understanding or realisation.",
        "example": "It was an epiphany — she finally understood how to use the present perfect.",
    },
    {
        "word": "Bittersweet",
        "phonetic": "/ˈbɪtəswiːt/",
        "part_of_speech": "adjective",
        "definition": "Evoking pleasure tinged with sadness or pain at the same time.",
        "example": "Graduating from the course was a bittersweet moment.",
    },
    {
        "word": "Awkward",
        "phonetic": "/ˈɔːkwəd/",
        "part_of_speech": "adjective",
        "definition": "Causing or feeling social discomfort in a way that is hard to describe precisely.",
        "example": "There was an awkward silence when nobody knew the answer.",
    },
    {
        "word": "Cosy",
        "phonetic": "/ˈkəʊzi/",
        "part_of_speech": "adjective",
        "definition": "Giving a feeling of comfort, warmth, and relaxed contentment.",
        "example": "They had a cosy conversation over tea after class.",
    },
    {
        "word": "Afterglow",
        "phonetic": "/ˈɑːftəɡləʊ/",
        "part_of_speech": "noun",
        "definition": "The pleasant feeling that lingers after a positive experience.",
        "example": "She was still in the afterglow of her first successful English presentation.",
    },
    {
        "word": "Daydream",
        "phonetic": "/ˈdeɪdriːm/",
        "part_of_speech": "verb / noun",
        "definition": "To indulge in a series of pleasant thoughts as a form of escape from reality.",
        "example": "He daydreamed about travelling through Scotland.",
    },
    {
        "word": "Flabbergasted",
        "phonetic": "/ˈflæbəɡɑːstɪd/",
        "part_of_speech": "adjective",
        "definition": "Completely astonished and lost for words.",
        "example": "She was flabbergasted when she passed the Cambridge exam with distinction.",
    },
    {
        "word": "Whimsy",
        "phonetic": "/ˈwɪmzi/",
        "part_of_speech": "noun",
        "definition": "Playful, quaint, or fanciful behaviour or humour.",
        "example": "The teacher's whimsy made every lesson memorable.",
    },
    {
        "word": "Overwhelmed",
        "phonetic": "/ˌəʊvəˈwelmd/",
        "part_of_speech": "adjective",
        "definition": "Completely submerged by an emotion or situation — too much to process at once.",
        "example": "She felt overwhelmed with joy when she received her results.",
    },
    {
        "word": "Closure",
        "phonetic": "/ˈkləʊʒə/",
        "part_of_speech": "noun",
        "definition": "A sense of resolution or completion at the end of something difficult.",
        "example": "Finishing the advanced course gave her a feeling of closure.",
    },
    {
        "word": "Mindfulness",
        "phonetic": "/ˈmaɪndflnəs/",
        "part_of_speech": "noun",
        "definition": "The practice of being fully present and aware in the current moment.",
        "example": "Mindfulness helped her focus during exam preparation.",
    },
    {
        "word": "Gobsmacked",
        "phonetic": "/ˈɡɒbsmækt/",
        "part_of_speech": "adjective",
        "definition": "So surprised that you are temporarily unable to speak.",
        "example": "He was gobsmacked when the teacher told him his accent was perfect.",
    },
    {
        "word": "Sonder",
        "phonetic": "/ˈsɒndər/",
        "part_of_speech": "noun",
        "definition": "The realisation that every stranger has a life as vivid and complex as your own.",
        "example": "Travelling abroad gave her a deep sense of sonder.",
    },
    {
        "word": "Serenity",
        "phonetic": "/səˈrenɪti/",
        "part_of_speech": "noun",
        "definition": "The state of being calm, peaceful, and untroubled.",
        "example": "The lake at Traful was a place of perfect serenity.",
    },
    {
        "word": "Eloquence",
        "phonetic": "/ˈeləkwəns/",
        "part_of_speech": "noun",
        "definition": "The ability to express ideas fluently and persuasively.",
        "example": "Her eloquence in English impressed everyone at the conference.",
    },
    {
        "word": "Procrastinate",
        "phonetic": "/prəˈkræstɪneɪt/",
        "part_of_speech": "verb",
        "definition": "To delay or postpone action, especially out of habitual carelessness or laziness.",
        "example": "Don't procrastinate — book your level test today!",
    },
    {
        "word": "Resilience",
        "phonetic": "/rɪˈzɪliəns/",
        "part_of_speech": "noun",
        "definition": "The ability to recover quickly from difficulties and keep going.",
        "example": "Learning a language requires resilience and patience.",
    },
    {
        "word": "Earnest",
        "phonetic": "/ˈɜːnɪst/",
        "part_of_speech": "adjective",
        "definition": "Sincere and serious in intention, with no trace of irony.",
        "example": "She made an earnest effort to improve her pronunciation every day.",
    },
    {
        "word": "Bubbly",
        "phonetic": "/ˈbʌbli/",
        "part_of_speech": "adjective",
        "definition": "Cheerful, lively, and full of enthusiasm — in a way that is infectious.",
        "example": "Her bubbly personality made her a natural English speaker.",
    },
    {
        "word": "Quirky",
        "phonetic": "/ˈkwɜːki/",
        "part_of_speech": "adjective",
        "definition": "Characterised by unusual or unexpected traits in a charming way.",
        "example": "English spelling is wonderfully quirky once you get used to it.",
    },
    {
        "word": "Nostalgia",
        "phonetic": "/nɒˈstældʒə/",
        "part_of_speech": "noun",
        "definition": "A sentimental longing for a past time, often idealised in memory.",
        "example": "Hearing that song filled her with nostalgia for her first English class.",
    },
    {
        "word": "Afterthought",
        "phonetic": "/ˈɑːftəθɔːt/",
        "part_of_speech": "noun",
        "definition": "Something added later that was not part of the original plan.",
        "example": "The vocabulary quiz was added as an afterthought, but it became everyone's favourite.",
    },
]
